In [1]:
# Author: José Alfredo de León
# Date: 19.07.2020

# Book: Dynamical Systems with Applications using Python, 2018
# Exercise 3

import numpy as np

Given that $$A = \begin{pmatrix} 1 & 2 & -1 \\ 0 & 1 & 0 \\ 3 & -1 & 2 \end{pmatrix},\ B = \begin{pmatrix} 1 & 2 & 3 \\ 1 & 1 & 2 \\ 0 & 1 & 2 \end{pmatrix},\ C = \begin{pmatrix} 2 & 1 & 1 \\ 0 & 1 & -1 \\ 4 & 2 & 2 \end{pmatrix}$$

In [10]:
A = np.array([[1,2,-1],[0,1,0],[3,-1,2]])
B = np.array([[1,2,3],[1,1,2],[0,1,2]])
C = np.array([[2,1,1],[0,1,-1],[4,2,2]])

(a) $$A + 4BC$$

In [24]:
A-4*np.matmul(B,C)

array([[-55, -34, -21],
       [-40, -23, -16],
       [-29, -21, -10]])

(b) inverse of each matrix if it exists;

In [14]:
np.linalg.inv(A)

array([[ 4.00000000e-01, -6.00000000e-01,  2.00000000e-01],
       [ 4.75809868e-17,  1.00000000e+00,  0.00000000e+00],
       [-6.00000000e-01,  1.40000000e+00,  2.00000000e-01]])

In [15]:
np.linalg.inv(B)

array([[ 0.,  1., -1.],
       [ 2., -2., -1.],
       [-1.,  1.,  1.]])

In [16]:
np.linalg.inv(C)

LinAlgError: Singular matrix

### Matrix C doesn't have inverse.

(c) $$A^3$$;

In [17]:
np.linalg.matrix_power(A,3)

array([[-11,   4,  -4],
       [  0,   1,   0],
       [ 12,  20,  -7]])

(d) the determinant of C;

In [19]:
np.linalg.det(C)

0.0

(e) the eigenvalues and eigenvectors of B.

### Eigenvalues of B:

In [23]:
np.linalg.eig(B)[0]

array([-0.37720285,  0.72610945,  3.65109341])

### Eigenvectors of B:

In [22]:
np.linalg.eig(B)[1]

array([[ 0.44287099,  0.71390288,  0.7763    ],
       [-0.82644005,  0.5508072 ,  0.53918151],
       [ 0.34765231, -0.43238189,  0.32656027]])

(each array is an eigenvector)